spring:
    datasource:
        url: jdbc:h2:mem:dev;DATABASE_TO_UPPER=false
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
    h2:
        console:
            enabled: true
    liquibase:
        change-log: classpath:database/liquibase-master.xml